default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres
  password: 'postgres'

development:
  <<: *default
  database: friends_secrets_development

test:
  <<: *default
  database: friends_secrets_test

production:
  <<: *default
  database: friends_secrets_production
